AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  scraping_from_lambda

  Sample SAM Template for scraping_from_lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ScrapingFromLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ScrapingFromLambda
      CodeUri: scraping_from_lambda/
      Handler: app.lambda_handler
      Runtime: ruby2.5
      Role: !GetAtt ScrapingFromLambdaFunctionIamRole.Arn
      MemorySize: 128
      ReservedConcurrentExecutions: 3
      Environment:
        Variables:
          Env: !Ref Env
          S3_URL: !Ref S3_URL
          S3_REGION: !Ref S3_REGION
          BucketName: !Ref BucketName
          SCRAPING_URL: !Ref SCRAPING_URL
      Layers:
        - !Ref GemsLayer
      Events:
        ScrapingFromLambdaEvent:
          Type: S3
          Properties:
            Bucket: !Ref BucketName
            Events: s3:ObjectCreated:*

  GemsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: ruby-serverless-crawling-gems-only-for-scraping_from_lambda
      Description: Gems Resource Layer
      ContentUri: ./ruby-serverless-crawling-gems

  ScrapingFromLambdaIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "scraping_from_lambda_policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "cloudwatch:*"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:ap-northeast-1:*:*"
              - Effect: Allow
                Action: "ses:*"
                Resource: "*"
              - Effect: Allow
                Action: "ec2:*"
                Resource: "*"
              - Effect: Allow
                Action: "cloudformation:*"
                Resource: "*"
              - Effect: Allow
                Action: "lambda:*"
                Resource: "*"
              - Effect: Allow
                Action: "s3:*"
                Resource:
                  - "arn:aws:s3:::test-bucket/*"

Parameters:
  # prod：本番環境 dev：開発環境（ローカル）
  Env:
    Type: String
    AllowedValues:
      - prod
      - dev
    Default: dev
  S3_URL:
    Type: String
    Default: None
  S3_REGION:
    Type: String
    Default: None
  BucketName:
    Type: String
    Default: test-bucket
  SCRAPING_URL:
    Type: String
    Default: 

