source "https://rubygems.org"

gem "selenium-webdriver"
gem "webdrivers"
gem "childprocess"
gem "nokogiri"
gem "rubyzip", "~> 1.3.0"

group :test do
  gem 'httparty'
  gem "test-unit"
  gem "mocha"
end
